Compile fixes for newer compilers (#105)
* Make MatchingCmp operator const

To fix compilation on gcc 15 / clang 21. Otherwise you get

/usr/include/c++/15/bits/stl_tree.h:2604:36: error: no match for call to ‘(const MatchingCmp) (const Matching* const&, const Matching* const&)’
 2604 |         if (!_M_impl._M_key_compare(_S_key(__x), __k))
      |              ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
...
src/e9tool/e9tool.cpp:434:10: note: candidate 1: ‘bool MatchingCmp::operator()(const Matching*, const Matching*)’ (near match)
  434 |     bool operator()(const Matching *m1, const Matching *m2)
      |          ^~~~~~~~
src/e9tool/e9tool.cpp:434:10: note: passing ‘const MatchingCmp*’ as ‘this’ argument discards qualifiers

* Fix stdatomic-fbsd.h for gcc 15

gcc 15 returns true for __has_feature(c_atomic), but doesn't have the
clang specific __c11_ intrinsics. Explicitly check for clang.

---------

Co-authored-by: Andi Kleen <andi@firstfloor.org>