Add [optional] C++ and type safety support.
Previously, call instrumentation can be written
in C and compiled using the e9compile.sh script.

However, there is no type safety, and if the
command-line options and C function definition
mismatch then things go wrong.

Worse, some arguments like op[i] can have a
different type depending on the instruction.

This commit introduces C++ support for call
instrumentation in addition to C.  Unlike C,
the C++ version supports type safety and
polymorphism.

Example using C [old-style]:

   $ ./e9compile.sh examples/print.c
   $ ./e9tool -M 'asm=j.*' \
     -A 'call entry(addr,asm,instr,size)@print' \
     xterm
   $ ./a.out
   Segmentation fault

It crashes because the argument order was wrong
(i.e., a type error).

But if we compile as C++ using (-x c++):

   $ ./e9compile.sh examples/print.c -x c++
   $ ./e9tool -M 'asm=j.*' \
     -A 'call entry(addr,asm,instr,size)@print' \
     xterm
   error: ...failed to find a symbol matching...

The type error is detected statically.

Polymorphism is also supported.  E.g., the C++
file can define:

   void entry(int16_t, int16_t *) { ... }
   void entry(int32_t, int32_t *) { ... }
   void entry(int64_t, int64_t *) { ... }

And the action:

  -A 'call entry(src[0], &dst[0])@bin'

will call the entry() function corresponding
to the types of src[0] and &dst[0].

C++ support is optional, and C is still
supported.